site_name: Eric Chan
site_url: https://errchh.github.io/
#repo_url: https://github.com/errchh/errchh.github.io
#edit_uri: edit/main/docs/
base_url: /errchh.github.io/
repo_name: errchh


nav:
  - Backgrounds: index.md
  - AI Projects:
      - p1: product_tagging.md
      - p2: skincare_classification.md
      - p3: ipr_check.md
  - Side Projects: commercial_image.md


theme:
  name: material
  language: en
  palette:
    primary: white
  font:
    text: "Martian Mono"
    code: "Martian Mono"
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
#    - navigation.sections
  icon:
    repo: fontawesome/brands/github


extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/errchh


markdown_extensions:
  - abbr
  - admonition
