site_name: Eric Chan
nav:
  - About: index.md
  - Key Projects:
      - Gen AI Product Tagging: gen-ai-tagging.md
      - Gen AI Skincare Classification: gen-ai-classification-skincare.md
      - Counterfeit Clothing Detection: counterfeit-classification.md
theme:
  name: material
  language: en
  palette:
    primary: white
  font:
    text: "IBM Plex Sans"
    code: "IBM Plex Mono"
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
plugins:
  - search:
      enabled: false
markdown_extensions:
  - abbr
  - admonition