site_name: Eric Chan
site_url: https://errchh.github.io/
repo_url: https://github.com/errchh/errchh.github.io
edit_uri: edit/main/docs/
base_url: /errchh.github.io/
nav:
  - About: index.md
  - Key Projects:
      - Gen AI Product Tagging: gen-ai-tagging.md
      - Gen AI Skincare Classification: gen-ai-classification-skincare.md
      - Counterfeit Clothing Detection: counterfeit-classification.md
theme:
  name: material
  language: en
  palette:
    primary: white
  font:
    text: "IBM Plex Sans"
    code: "IBM Plex Mono"
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
markdown_extensions:
  - abbr
  - admonition
