[project]
name = "errchh-github-io"
version = "0.1.0"
description = "Portfolio webpage using MKdocs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
]
